title: Yi Zhang 张        懿
logo: /images/yi_photo.jpg 
description: a CS Ph.D. student at Johns Hopkins
google_analytics: UA-153053613-1
show_downloads: false
theme: jekyll-theme-minimal

#gems:
# - jekyll-mentions
